name: Build
on: [ push, workflow_dispatch ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install gcc-11-multilib g++-11-multilib gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - run: dotnet run -c Release -- -v Diagnostic

      - uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: out/*.nupkg
